spring.application.name=KafkaPractice2

server.port=8081

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=0
spring.kafka.producer.batch-size=1000
spring.kafka.producer.properties.linger.ms=100
spring.kafka.producer.retries=3
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-web
spring.kafka.consumer.properties.spring.json.trusted.packages=*